name: Test the code coverage

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip version
        run: |
          python -m pip install -U pip

      - name: Install dependencies
        run: |
          sudo apt-get install python-setuptools lcov libboost-dev libgmp-dev

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "14.0"
          directory: ${{ runner.temp }}/llvm

      - name: Install Z3
        run: |
          sudo apt-get install libz3-dev
          python -m pip install z3-solver

      - name: Install Bitwuzla
        run: |
          git clone https://github.com/bitwuzla/bitwuzla
          cd bitwuzla
          ./contrib/setup-cadical.sh
          ./contrib/setup-btor2tools.sh
          ./configure.sh production --only-cadical --no-symfpu --no-testing --shared
          sudo make -C build install
          cd ..

      - name: Install Capstone
        run: |
          wget https://github.com/aquynh/capstone/archive/4.0.2.tar.gz
          tar -xf ./4.0.2.tar.gz
          cd ./capstone-4.0.2
          bash ./make.sh
          sudo make install
          cd ../

      - name: Install Unicorn
        run: |
          python -m pip install unicorn

      - name: Install LIEF
        run: |
          python -m pip install lief

      - name: Compile Triton
        run: |
          mkdir ./build
          cd ./build
          cmake -DGCOV=on -DZ3_INTERFACE=on -DBITWUZLA_INTERFACE=on -DLLVM_INTERFACE=on -DCMAKE_PREFIX_PATH=${{env.LLVM_PATH}} ..
          sudo make -j3 install

      - name: Unittests
        run: |
          make -C build check
          bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
